#!/usr/bin/env bash


read -p "Qual seu nome? " nome

read -p "Qual sua altura? " altura

read -p "Qual sua escolaridade? " escolaridade

echo -e "O seu nome é: $nome\n"
echo -e "A sua altura é: $altura\n"
echo -e "A sua escolaridade é: $escolaridade\n"

